version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elastic-node1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - elastic-net
  kibana:
    image: kibana.elastalert
    depends_on:
      - elasticsearch
    container_name: kibana
    volumes:
      - /e/Dev/Projects/elk-std/kibana/kibana.yml\:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    expose:
      - "5601"
    links:
      - elasticsearch:elasticsearch
    networks:
      - elastic-net
  seq:
    image: datalust/seq:5
    restart: always
    container_name: seq
    environment:
        - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    ports:
      - 8080:80
      - 5341:5341
    expose:
      - "8080"
networks:
  elastic-net:
volumes:
  elastic-data1:
  seq-data: